### ISSUE TITLE
Missing text on Clean install UI

### ISSUE THREAD

**Issue by suciptoid** [BlankOn/blankon-installer#108]
<img width="548" alt="screen shot 2016-10-15 at 17 03 25" src="https://cloud.githubusercontent.com/assets/1310895/19409255/3d95c2ae-92fa-11e6-82d4-cc837159f88e.png">

**Comment by herpiko** [comment]
@showcheap These strings handled by `localization.js` in different repository, see : https://github.com/BlankOn/blankon-installer-ui/blob/master/src/app/localization.js

Would you like to solve this issue?

**Comment by suciptoid** [comment]
@herpiko Ok, got it.

**Comment by suciptoid** [comment]
I've submitted issue in wrong repo 😆 

https://github.com/BlankOn/blankon-installer-ui/pull/63
