### ISSUE TITLE
Aktifkan intel p-state untuk perangkat dengan prosesor tertentu

### ISSUE THREAD

**Issue by diorahman** [BlankOn/blankon-installer#11]
Referensi: 
- http://www.webupd8.org/2014/04/prevent-your-laptop-from-overheating.html
- https://www.kernel.org/doc/Documentation/cpu-freq/intel-pstate.txt

**Comment by herpiko** [comment]
Sudah aktif secara otomatis di broadwell.

**Comment by herpiko** [comment]
- sandy : :white_check_mark: 
- ivy : :white_check_mark: 
- haswell : :white_check_mark: 
- broadwell : :white_check_mark: 
- skylake

**Comment by herpiko** [comment]
Terima kasih.
