### ISSUE TITLE
Membuat berkas id instalasi

### ISSUE THREAD

**Issue by mdamt** [BlankOn/blankon-installer#12]
Letakkan di $TARGET/etc/installation-id.txt

Isinya: $DIST-$ARCH-$UUID

$DIST=tambora,suroboyo,dst
$ARCH=i386 | amd64 | armhf
$UUID=uuid biasa hasil perintah `uuidgen`

**Comment by herpiko** [comment]
resolved by commit 781f2990e9fa21e1f22951400a59dd7eb4d0495d

**Comment by mdamt** [comment]
Isinya harus 1 baris: $DIST-$ARCH-$UUID

contoh:
tambora-i386-f80953d3-09f5-4e90-b27c-db9d54d5bc91

**Comment by herpiko** [comment]
UUID pakai separator "-", tetap pakai separator "-" juga untuk ketiga variabel tersebut (misal nanti mau displit) ?

**Comment by mdamt** [comment]
Iya pak

**Comment by herpiko** [comment]
resolved 73b56428a164b3a43fc14ce63db2c33e893eb36a
