### ISSUE TITLE
Mesti lolos CI

### ISSUE THREAD

**Issue by herpiko** [BlankOn/blankon-installer#26]

**Comment by hikmahgumelar** [comment]
TravisCI lolos dengan menggunakan libparted 3.2 di ubuntu precise 12.04
![image](https://cloud.githubusercontent.com/assets/4201453/16739820/242aa002-47c6-11e6-9f4c-82047e0739a8.png)
@herpiko @mdamt

**Comment by hikmahgumelar** [comment]
TravisCI Passed
