### ISSUE TITLE
Dukungan EFI

### ISSUE THREAD

**Issue by herpiko** [BlankOn/blankon-installer#9]

**Comment by mdamt** [comment]
Sebagai prasyarat, paket blankon-installer perlu perubahan:

```
Depends: grub-pc
```

menjadi

```
Depends: grub-pc | grub-efi-amd64 | grub-efi-i386 
```

Mohon dibantu pak @dotovr

**Comment by emhaye** [comment]
Dari sisi paket sudah oke pak, sudah saya tambahkan dependsnya

**Comment by emhaye** [comment]
Perubahan depends grub
http://irgsh.blankonlinux.or.id/build/7353/

**Comment by diorahman** [comment]
:+1:

**Comment by aftian** [comment]
pak fiko, bisa minta tolong, jika installer mendeteksi efi maka pasang grub-efi-amd64 [amd64], pasang grub-efi-i386 [i386], ini faket sudah ada di cd tinggal fasang saja.

**Comment by herpiko** [comment]
Siap pak MDAMT.

**Comment by herpiko** [comment]
Done.
